name: 'flutter-test-action'
description: 'Run `flutter test` as a check run'
author: 'PRODYNA'
inputs:
  project:
    required: false
    description: 'path to flutter project'
    default: '.'
  token:
    required: true
    description: 'GitHub API Token (PAT or GITHUB_TOKEN)'
runs:
  using: 'node16'
  main: 'dist/index.js'
